### ISSUE TITLE
Bug: Offline tests executed from forks fail Azure authentication step

### ISSUE THREAD

**Issue by FKolwa** [redhatcloudx/cloud-image-directory#307]
Example: https://github.com/redhatcloudx/rhelocator/actions/runs/4058595003/jobs/6992364595

Check the authentication mock and make sure that the offline tests complete without throwing an "Unable to authenticate" exception.

- [x] fix azure mocks
- [x] fix aws mocks
- [x] fix google mocks
- [x] remove live tests

**Comment by miyunari** [comment]
The aws and google mocks are working, so I close the issue now :fireworks: :rocket:
