### ISSUE TITLE
Make image locator more resilient against timeout failure

### ISSUE THREAD

**Issue by FKolwa** [redhatcloudx/cloud-image-directory#80]
Cloud provider API endpoints have to handle a lot of traffic.
We need to make sure our API calls take this into account and establish a sane retry period to make sure we can handle the occasional performance drops.

**Comment by miyunari** [comment]
Hey @FKolwa, 
I tried to write down the current architecture and what we could maybe change to improve the behavior of the ci-pipeline. Would be nice to get some feedback on the document :) 

cc: @major 

1: https://docs.google.com/document/d/1qcBBZPMUFUPhSxtqplYWJt6u9jdPhqwOxVQjaq_N4HE/edit

**Comment by FKolwa** [comment]
Hint: Please add retry (as discussed)
